#ifndef SYNCPROCESSORPROVIDER_H
#define SYNCPROCESSORPROVIDER_H

#include "interface.syncprocessorcreator.h"
#include <QObject>

/*!
 * \brief The SyncProcessorProvider class is a fabric of sync processors
 *
 * QML sends required processor typeId from table generated by this class.
 * createProcessor function invokes Creator linked to particular typeId.
 */
class SyncProcessorProvider
{
        Q_DISABLE_COPY(SyncProcessorProvider)
    public:
        static SyncProcessorProvider& getInstance();

        /*!
         * \brief createProcessor
         * \param processorTypeId
         * \param data - additional data (folder name, connection title, etc)
         * \return instance of processor with typeId with interface ISyncProcessor
         */
        ISyncProcessor* createProcessor(int processorTypeId, QString data);

        /*!
         * \brief addCreator registers new creator (and processor type)
         * \param creator
         */
        void addCreator(ISyncProcessorCreator* creator);

        QStringList getAvailableProcessorTypes();

    private:
        SyncProcessorProvider() {}

        QList<ISyncProcessorCreator*> creators;
};

#endif // SYNCPROCESSORPROVIDER_H
